# Week 1 — Problem Definition & Dataset Exploration (Easy Version)
### ML Project (Common Project Model — Phase 1)
**Dataset:** Vehicle Insurance Fraud Data
**Library used:** Pandas (simple, beginner-friendly commands)
**Student Name:** _______________
**Roll No / Enrolment No:** _______________
**Date:** _______________

---

## 1. Problem Statement

We want to predict whether an insurance claim is **fraudulent (Y)** or **genuine (N)**, using information about the driver, vehicle, and claim (age, income, vehicle details, claim amount, etc.).

**Target Column:** `fraud reported`

**Type of Problem:** Classification (Yes/No prediction)

## 2. Import Pandas

In [21]:
import pandas as pd

## 3. Load the Dataset

In [22]:
df = pd.read_csv('insurance_fraud_data.csv')
df.head()

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
0,414724,39,M,1,73,58612.8,1,0,Own,50048,...,Large,24360.59273,silver,26633.27819,5196.552552,1000,1406.91,8.641800,5,N
1,269568,33,M,1,72,35936.0,0,1,Own,50006,...,Medium,23457.35282,black,26707.46021,7957.267641,2000,1415.74,10.009761,5,Y
2,974592,31,M,1,76,84940.8,1,1,Own,15021,...,Medium,19752.42523,gray,15279.38583,3014.110884,1000,1199.44,8.264032,3,N
3,995328,53,F,1,93,73526.4,0,1,Own,85027,...,Medium,32910.34224,red,20909.27772,5671.599025,500,708.64,9.235943,4,N
4,1140480,41,M,1,87,59403.2,1,0,Own,80046,...,Medium,28570.37675,red,34493.97997,4064.569489,1000,1187.96,10.259629,2,N

---
## 4. Simple Questions (Easy Level)

Just run each cell and note down what you observe below it. No advanced code, just basic pandas.

### Q1. How many rows and columns are in the dataset?

In [23]:
df.shape

(12002, 29)

**My Observation:** _write here_

### Q2. What are the column names?

In [24]:
df.columns

Index(['claim_number', 'age_of_driver', 'gender', 'marital_status',
       'safety_rating', 'annual_income', 'high_education', 'address_change',
       'property_status', 'zip_code', 'claim_date', 'claim_day_of_week',
       'accident_site', 'past_num_of_claims', 'witness_present', 'liab_prct',
       'channel', 'police_report', 'age_of_vehicle', 'vehicle_category',
       'vehicle_price', 'vehicle_color', 'total_claim', 'injury_claim',
       'policy deductible', 'annual premium', 'days open', 'form defects',
       'fraud reported'],
      dtype='object')

**My Observation:** _write here_

### Q3. What do the first 5 rows look like?

In [25]:
df.head()

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
0,414724,39,M,1,73,58612.8,1,0,Own,50048,...,Large,24360.59273,silver,26633.27819,5196.552552,1000,1406.91,8.641800,5,N
1,269568,33,M,1,72,35936.0,0,1,Own,50006,...,Medium,23457.35282,black,26707.46021,7957.267641,2000,1415.74,10.009761,5,Y
2,974592,31,M,1,76,84940.8,1,1,Own,15021,...,Medium,19752.42523,gray,15279.38583,3014.110884,1000,1199.44,8.264032,3,N
3,995328,53,F,1,93,73526.4,0,1,Own,85027,...,Medium,32910.34224,red,20909.27772,5671.599025,500,708.64,9.235943,4,N
4,1140480,41,M,1,87,59403.2,1,0,Own,80046,...,Medium,28570.37675,red,34493.97997,4064.569489,1000,1187.96,10.259629,2,N

**My Observation:** _write here_

### Q4. What do the last 5 rows look like?

In [26]:
df.tail()

,claim_number,age_of_driver,gender,marital_status,safety_rating,annual_income,high_education,address_change,property_status,zip_code,...,vehicle_category,vehicle_price,vehicle_color,total_claim,injury_claim,policy deductible,annual premium,days open,form defects,fraud reported
11997,621727488,34,M,1,88,66505.6,1,1,Rent,20134,...,Large,24134.334750,red,34516.53474,6639.049156,1000,1622.67,12.449888,3,N
11998,621810432,65,F,1,97,23315.2,1,0,Rent,20134,...,Compact,57417.739270,gray,26718.21104,3382.4126,500,1055.60,9.730108,6,Y
11999,621872640,64,F,1,87,66505.6,0,1,Own,20142,...,Large,20231.723630,other,27015.87981,7475.901535,2000,1155.97,8.386094,2,N
12000,621914112,34,F,1,70,76409.6,1,0,Own,20109,...,Compact,21900.031920,black,16122.91954,3838.951645,1000,1726.91,10.314865,5,N
12001,621955584,45,M,1,61,70915.2,1,0,Rent,15044,...,Medium,8291.858346,red,26825.84418,5236.564274,500,1232.57,9.116981,4,N

**My Observation:** _write here_

### Q5. What is the data type of each column (number, text, etc.)?

In [27]:
df.dtypes

claim_number            int64
age_of_driver           int64
gender                 object
marital_status         object
safety_rating           int64
annual_income         float64
high_education          int64
address_change          int64
property_status        object
zip_code                int64
claim_date             object
claim_day_of_week      object
accident_site          object
past_num_of_claims      int64
witness_present        object
liab_prct               int64
channel                object
police_report           int64
age_of_vehicle         object
vehicle_category       object
vehicle_price         float64
vehicle_color          object
total_claim           float64
injury_claim           object
policy deductible       int64
annual premium        float64
days open             float64
form defects            int64
fraud reported         object
dtype: object

**My Observation:** _write here_

### Q6. Is there any missing (empty) data in the dataset?

In [28]:
df.isnull().sum()

claim_number          0
age_of_driver         0
gender                0
marital_status        0
safety_rating         0
annual_income         0
high_education        0
address_change        0
property_status       0
zip_code              0
claim_date            0
claim_day_of_week     0
accident_site         0
past_num_of_claims    0
witness_present       0
liab_prct             0
channel               0
police_report         0
age_of_vehicle        0
vehicle_category      0
vehicle_price         0
vehicle_color         0
total_claim           0
injury_claim          0
policy deductible     0
annual premium        0
days open             0
form defects          0
fraud reported        8
dtype: int64

**My Observation:** _write here_

### Q7. What is the average (mean) age of drivers?

In [29]:
df['age_of_driver'].mean()

np.float64(43.52516247292118)

**My Observation:** _write here_

### Q8. What is the youngest and oldest driver age in the dataset?

In [30]:
print('Youngest:', df['age_of_driver'].min())
print('Oldest:', df['age_of_driver'].max())

Youngest: 19
Oldest: 278

**My Observation:** _write here_

### Q9. What is the average annual income of policyholders?

In [31]:
df['annual_income'].mean()

np.float64(63658.22653357774)

**My Observation:** _write here_

### Q10. What is the average total claim amount?

In [32]:
df['total_claim'].mean()

np.float64(22861.534958498665)

**My Observation:** _write here_

### Q11. How many claims were fraudulent (Y) vs genuine (N)?

In [33]:
df['fraud reported'].value_counts()

fraud reported
N    9043
Y    2951
Name: count, dtype: int64

**My Observation:** _write here_

### Q12. What are the different vehicle categories in the dataset?

In [34]:
df['vehicle_category'].unique()

array(['Large', 'Medium', 'Compact'], dtype=object)

**My Observation:** _write here_

### Q13. What are the different claim channels, and how many claims came through each?

In [35]:
df['channel'].value_counts()

channel
Broker    6370
Phone     3840
Online    1792
Name: count, dtype: int64

**My Observation:** _write here_

### Q14. How many claims had a witness present?

In [36]:
df['witness_present'].value_counts()

witness_present
0    9070
1    2844
*      88
Name: count, dtype: int64

**My Observation:** _write here_

### Q15. How many claims had a police report filed?

In [37]:
df['police_report'].value_counts()

police_report
1    7214
0    4788
Name: count, dtype: int64

**My Observation:** _write here_

### Q16. What is the simple statistical summary (min, max, mean, etc.) of all number columns?

In [38]:
df.describe()

,claim_number,age_of_driver,safety_rating,annual_income,high_education,address_change,zip_code,past_num_of_claims,liab_prct,police_report,vehicle_price,total_claim,policy deductible,annual premium,days open,form defects
count,1.200200e+04,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000,12002.000000
mean,3.119801e+08,43.525162,73.702966,63658.226534,0.698134,0.576737,49762.387269,0.494918,49.770122,0.601066,22925.335594,22861.534958,1011.039827,1268.140663,8.799198,3.969588
std,1.795997e+08,12.201298,15.378967,17289.704559,0.459087,0.494097,29133.180765,0.956002,33.581191,0.489699,12108.888412,12197.334761,562.099581,231.670671,2.413533,1.986915
min,1.866240e+05,19.000000,2.000000,-1.600000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2261.507903,2583.428985,500.000000,433.330000,2.303305,0.000000
25%,1.561887e+08,35.000000,66.000000,56899.200000,0.000000,0.000000,20111.000000,0.000000,18.000000,0.000000,14087.559950,13832.784382,500.000000,1082.360000,8.025550,3.000000
50%,3.121908e+08,43.000000,76.000000,60899.200000,1.000000,1.000000,50027.000000,0.000000,50.000000,1.000000,20642.029325,20508.293695,1000.000000,1239.060000,9.268787,4.000000
75%,4.677938e+08,51.000000,85.000000,64697.600000,1.000000,1.000000,80036.750000,1.000000,82.000000,1.000000,29293.641235,29205.553660,1000.000000,1383.490000,10.307928,5.000000
max,6.220385e+08,278.000000,100.000000,257313.600000,1.000000,1.000000,85083.000000,6.000000,100.000000,1.000000,106991.684500,101818.964200,2000.000000,2047.590000,15.177169,13.000000

**My Observation:** _write here_